-- =============================================================================
-- Migration: 001_add_latency_breakdowns
--
-- Purpose:
-- - Add per-query-type and read/write latency summaries to TEST_RESULTS
-- - Extend QUERY_EXECUTIONS to store per-operation app timings + Snowflake timings
--
-- This file is rerunnable (ADD COLUMN IF NOT EXISTS).
-- =============================================================================

USE DATABASE UNISTORE_BENCHMARK;
USE SCHEMA TEST_RESULTS;

-- -----------------------------------------------------------------------------
-- Extend QUERY_EXECUTIONS (per-operation log)
-- -----------------------------------------------------------------------------
ALTER TABLE IF EXISTS QUERY_EXECUTIONS ADD COLUMN IF NOT EXISTS QUERY_KIND VARCHAR(50);
ALTER TABLE IF EXISTS QUERY_EXECUTIONS ADD COLUMN IF NOT EXISTS WORKER_ID INTEGER;
ALTER TABLE IF EXISTS QUERY_EXECUTIONS ADD COLUMN IF NOT EXISTS WARMUP BOOLEAN DEFAULT FALSE;

-- End-to-end latency measured by the app (what customers experience)
ALTER TABLE IF EXISTS QUERY_EXECUTIONS ADD COLUMN IF NOT EXISTS APP_ELAPSED_MS FLOAT;

-- Snowflake timings (from INFORMATION_SCHEMA.QUERY_HISTORY)
ALTER TABLE IF EXISTS QUERY_EXECUTIONS ADD COLUMN IF NOT EXISTS SF_TOTAL_ELAPSED_MS FLOAT;
ALTER TABLE IF EXISTS QUERY_EXECUTIONS ADD COLUMN IF NOT EXISTS SF_EXECUTION_MS FLOAT;
ALTER TABLE IF EXISTS QUERY_EXECUTIONS ADD COLUMN IF NOT EXISTS SF_COMPILATION_MS FLOAT;
ALTER TABLE IF EXISTS QUERY_EXECUTIONS ADD COLUMN IF NOT EXISTS SF_QUEUED_OVERLOAD_MS FLOAT;
ALTER TABLE IF EXISTS QUERY_EXECUTIONS ADD COLUMN IF NOT EXISTS SF_QUEUED_PROVISIONING_MS FLOAT;
ALTER TABLE IF EXISTS QUERY_EXECUTIONS ADD COLUMN IF NOT EXISTS SF_TX_BLOCKED_MS FLOAT;
ALTER TABLE IF EXISTS QUERY_EXECUTIONS ADD COLUMN IF NOT EXISTS SF_BYTES_SCANNED BIGINT;
ALTER TABLE IF EXISTS QUERY_EXECUTIONS ADD COLUMN IF NOT EXISTS SF_ROWS_PRODUCED BIGINT;
ALTER TABLE IF EXISTS QUERY_EXECUTIONS ADD COLUMN IF NOT EXISTS SF_ROWS_INSERTED BIGINT;
ALTER TABLE IF EXISTS QUERY_EXECUTIONS ADD COLUMN IF NOT EXISTS SF_ROWS_UPDATED BIGINT;
ALTER TABLE IF EXISTS QUERY_EXECUTIONS ADD COLUMN IF NOT EXISTS SF_ROWS_DELETED BIGINT;

-- Derived overhead estimate
ALTER TABLE IF EXISTS QUERY_EXECUTIONS ADD COLUMN IF NOT EXISTS APP_OVERHEAD_MS FLOAT;

-- -----------------------------------------------------------------------------
-- Extend TEST_RESULTS (one row per test run, customer-facing summary)
-- -----------------------------------------------------------------------------
-- Read vs write percentiles (end-to-end)
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS READ_P50_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS READ_P95_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS READ_P99_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS READ_MIN_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS READ_MAX_LATENCY_MS FLOAT;

ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS WRITE_P50_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS WRITE_P95_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS WRITE_P99_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS WRITE_MIN_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS WRITE_MAX_LATENCY_MS FLOAT;

-- Per query kind (end-to-end)
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS POINT_LOOKUP_P50_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS POINT_LOOKUP_P95_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS POINT_LOOKUP_P99_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS POINT_LOOKUP_MIN_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS POINT_LOOKUP_MAX_LATENCY_MS FLOAT;

ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS RANGE_SCAN_P50_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS RANGE_SCAN_P95_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS RANGE_SCAN_P99_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS RANGE_SCAN_MIN_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS RANGE_SCAN_MAX_LATENCY_MS FLOAT;

ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS INSERT_P50_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS INSERT_P95_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS INSERT_P99_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS INSERT_MIN_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS INSERT_MAX_LATENCY_MS FLOAT;

ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS UPDATE_P50_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS UPDATE_P95_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS UPDATE_P99_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS UPDATE_MIN_LATENCY_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS UPDATE_MAX_LATENCY_MS FLOAT;

-- Overhead summaries (derived)
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS APP_OVERHEAD_P50_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS APP_OVERHEAD_P95_MS FLOAT;
ALTER TABLE IF EXISTS TEST_RESULTS ADD COLUMN IF NOT EXISTS APP_OVERHEAD_P99_MS FLOAT;

SELECT 'Migration 001_add_latency_breakdowns applied' AS STATUS;




