version: '3.45'

set: [pipefail]

vars:
  BASE_URL: '{{.BASE_URL | default "http://127.0.0.1:8000"}}'
  MAX_WAIT_SECONDS: '{{.MAX_WAIT_SECONDS | default "1800"}}'
  POLL_INTERVAL_SECONDS: '{{.POLL_INTERVAL_SECONDS | default "5"}}'
  METRICS_WAIT_SECONDS: '{{.METRICS_WAIT_SECONDS | default "60"}}'
  DURATION_SECONDS: '{{.DURATION_SECONDS | default "45"}}'
  WARMUP_SECONDS: '{{.WARMUP_SECONDS | default "0"}}'
  SMOKE_CONCURRENCY: '{{.SMOKE_CONCURRENCY | default "5"}}'
  SMOKE_ROWS: '{{.SMOKE_ROWS | default "300"}}'

tasks:
  default:
    desc: "List available tasks"
    cmds:
      - task --list

  css:build:
    desc: "Build Tailwind CSS (minified)"
    preconditions:
      - sh: command -v uv
        msg: "uv not found. Install from https://docs.astral.sh/uv/"
    cmds:
      - uv run tailwindcss -i backend/static/css/input.css -o backend/static/css/tailwind.css --minify

  css:watch:
    desc: "Watch and rebuild Tailwind CSS on changes"
    preconditions:
      - sh: command -v uv
        msg: "uv not found. Install from https://docs.astral.sh/uv/"
    cmds:
      - uv run tailwindcss -i backend/static/css/input.css -o backend/static/css/tailwind.css --watch

  css:dev:
    desc: "Build Tailwind CSS (unminified, for debugging)"
    preconditions:
      - sh: command -v uv
        msg: "uv not found. Install from https://docs.astral.sh/uv/"
    cmds:
      - uv run tailwindcss -i backend/static/css/input.css -o backend/static/css/tailwind.css

  test:variations:smoke:
    desc: "Run short 4-variation smoke checks via API (override with DURATION_SECONDS=5)"
    preconditions:
      - sh: command -v uv
        msg: "uv not found. Install from https://docs.astral.sh/uv/"
    cmds:
      - BASE_URL="{{.BASE_URL}}" MAX_WAIT_SECONDS="300" POLL_INTERVAL_SECONDS="{{.POLL_INTERVAL_SECONDS}}" METRICS_WAIT_SECONDS="{{.METRICS_WAIT_SECONDS}}" DURATION_SECONDS="{{.DURATION_SECONDS}}" WARMUP_SECONDS="{{.WARMUP_SECONDS}}" SMOKE_CONCURRENCY="{{.SMOKE_CONCURRENCY}}" SMOKE_ROWS="{{.SMOKE_ROWS}}" uv run python scripts/run_variation_smoke.py

  test:variations:smoke:long:
    desc: "Run long 4-variation smoke checks via API (5min duration, 10s warmup)"
    preconditions:
      - sh: command -v uv
        msg: "uv not found. Install from https://docs.astral.sh/uv/"
    cmds:
      - BASE_URL="{{.BASE_URL}}" MAX_WAIT_SECONDS="{{.MAX_WAIT_SECONDS}}" POLL_INTERVAL_SECONDS="{{.POLL_INTERVAL_SECONDS}}" METRICS_WAIT_SECONDS="{{.METRICS_WAIT_SECONDS}}" DURATION_SECONDS="300" WARMUP_SECONDS="10" SMOKE_CONCURRENCY="10" SMOKE_ROWS="{{.SMOKE_ROWS}}" uv run python scripts/run_variation_smoke.py

  test:variations:setup:
    desc: "Create smoke data tables + templates (no tests)"
    preconditions:
      - sh: command -v uv
        msg: "uv not found. Install from https://docs.astral.sh/uv/"
    cmds:
      - BASE_URL="{{.BASE_URL}}" DURATION_SECONDS="{{.DURATION_SECONDS}}" WARMUP_SECONDS="{{.WARMUP_SECONDS}}" SMOKE_CONCURRENCY="{{.SMOKE_CONCURRENCY}}" SMOKE_ROWS="{{.SMOKE_ROWS}}" uv run python scripts/run_variation_smoke.py --setup-only

  test:variations:cleanup:
    desc: "Drop smoke data tables + templates (no tests)"
    preconditions:
      - sh: command -v uv
        msg: "uv not found. Install from https://docs.astral.sh/uv/"
    cmds:
      - BASE_URL="{{.BASE_URL}}" uv run python scripts/run_variation_smoke.py --cleanup-only

  # ==========================================================================
  # E2E Tests (Real Database + WebSocket + Browser)
  # ==========================================================================
  
  test:unit:
    desc: "Run unit tests (mocked, fast)"
    preconditions:
      - sh: command -v uv
        msg: "uv not found. Install from https://docs.astral.sh/uv/"
    cmds:
      - uv run pytest tests/ -v --ignore=tests/e2e -m "not e2e"

  test:e2e:
    desc: "Run all E2E tests (requires E2E schema setup + running server)"
    preconditions:
      - sh: command -v uv
        msg: "uv not found. Install from https://docs.astral.sh/uv/"
    cmds:
      - E2E_TEST=1 uv run pytest tests/e2e/ -v --ignore=tests/e2e/browser -m "not browser"

  test:e2e:api:
    desc: "Run E2E API integration tests only"
    preconditions:
      - sh: command -v uv
        msg: "uv not found. Install from https://docs.astral.sh/uv/"
    cmds:
      - E2E_TEST=1 uv run pytest tests/e2e/test_run_lifecycle.py -v

  test:e2e:websocket:
    desc: "Run E2E WebSocket streaming tests only"
    preconditions:
      - sh: command -v uv
        msg: "uv not found. Install from https://docs.astral.sh/uv/"
    cmds:
      - E2E_TEST=1 uv run pytest tests/e2e/test_websocket_streaming.py -v

  test:e2e:browser:
    desc: "Run E2E browser tests with Playwright (requires playwright install)"
    preconditions:
      - sh: command -v uv
        msg: "uv not found. Install from https://docs.astral.sh/uv/"
    cmds:
      - E2E_TEST=1 uv run pytest tests/e2e/browser/ -v --browser chromium

  test:e2e:all:
    desc: "Run complete E2E test suite (API + WebSocket + Browser)"
    preconditions:
      - sh: command -v uv
        msg: "uv not found. Install from https://docs.astral.sh/uv/"
    cmds:
      - task: test:e2e
      - task: test:e2e:browser

  test:e2e:setup:
    desc: "Set up E2E test schema in Snowflake"
    preconditions:
      - sh: command -v uv
        msg: "uv not found. Install from https://docs.astral.sh/uv/"
    cmds:
      - echo "Setting up E2E test schema..."
      - uv run python -c "from backend.setup_schema import execute_sql_statements; import snowflake.connector; from backend.config import settings; conn = snowflake.connector.connect(account=settings.SNOWFLAKE_ACCOUNT, user=settings.SNOWFLAKE_USER, password=settings.SNOWFLAKE_PASSWORD, warehouse=settings.SNOWFLAKE_WAREHOUSE, role=settings.SNOWFLAKE_ROLE); cursor = conn.cursor(); sql = open('sql/schema/e2e_test_schema.sql').read(); execute_sql_statements(cursor, sql); cursor.close(); conn.close(); print('✅ E2E schema setup complete')"

  test:e2e:cleanup:
    desc: "Clean up E2E test data (reset between runs)"
    preconditions:
      - sh: command -v uv
        msg: "uv not found. Install from https://docs.astral.sh/uv/"
    cmds:
      - uv run python -c "import snowflake.connector; from backend.config import settings; conn = snowflake.connector.connect(account=settings.SNOWFLAKE_ACCOUNT, user=settings.SNOWFLAKE_USER, password=settings.SNOWFLAKE_PASSWORD, warehouse=settings.SNOWFLAKE_WAREHOUSE, role=settings.SNOWFLAKE_ROLE, database='FLAKEBENCH', schema='E2E_TEST'); cursor = conn.cursor(); cursor.execute('CALL E2E_CLEANUP()'); print(cursor.fetchone()[0]); cursor.close(); conn.close()"

  test:e2e:server:
    desc: "Start server for E2E tests (port 8765, E2E_TEST schema)"
    preconditions:
      - sh: command -v uv
        msg: "uv not found. Install from https://docs.astral.sh/uv/"
    cmds:
      - E2E_TEST=1 RESULTS_SCHEMA=E2E_TEST uv run uvicorn backend.main:app --host 127.0.0.1 --port 8765 --reload

  test:e2e:quick:
    desc: "Quick E2E smoke test (API only, no slow tests)"
    preconditions:
      - sh: command -v uv
        msg: "uv not found. Install from https://docs.astral.sh/uv/"
    cmds:
      - E2E_TEST=1 uv run pytest tests/e2e/test_run_lifecycle.py -v -m "not slow" -x

  playwright:install:
    desc: "Install Playwright browsers for E2E browser tests"
    preconditions:
      - sh: command -v uv
        msg: "uv not found. Install from https://docs.astral.sh/uv/"
    cmds:
      - uv add playwright pytest-playwright
      - uv run playwright install chromium
