-- FlakeBench SPCS Guest User Setup
-- Creates a PERSON user "FLAKEBENCH" with password + PAT, scoped to ONLY access the SPCS app endpoint.
-- Requires: ACCOUNTADMIN
-- Account: SFSENORTHAMERICA-RGOLDIN_AWS1 (ZPB65314)
-- Executed: 2026-03-20
--
-- NOTE: Account-level auth policy (SECURITY_NETWORK_DB.POLICIES.ACCOUNT_MFA_AUTH_POLICY)
--       enforces MFA_ENROLLMENT = REQUIRED for all password logins.
--       Browser login requires MFA enrollment. PAT access works without MFA.

USE ROLE ACCOUNTADMIN;

-- 1. Create a role with ONLY service endpoint access
CREATE ROLE IF NOT EXISTS FLAKEBENCH_APP_GUEST_RL;
GRANT ROLE FLAKEBENCH_APP_GUEST_RL TO ROLE SECURITYADMIN;

-- 2. Create a PERSON user (interactive login + PAT)
CREATE USER IF NOT EXISTS FLAKEBENCH
  TYPE = PERSON
  PASSWORD = 'FlakeBench2026!'
  DEFAULT_ROLE = FLAKEBENCH_APP_GUEST_RL
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE FLAKEBENCH_APP_GUEST_RL TO USER FLAKEBENCH;

-- 3. Create a network policy (required for PATs)
CREATE NETWORK RULE IF NOT EXISTS FLAKEBENCH.PUBLIC.FLAKEBENCH_GUEST_NR
  MODE = INGRESS
  TYPE = IPV4
  VALUE_LIST = ('0.0.0.0/0');

CREATE NETWORK POLICY IF NOT EXISTS FLAKEBENCH_GUEST_NP
  ALLOWED_NETWORK_RULE_LIST = (FLAKEBENCH.PUBLIC.FLAKEBENCH_GUEST_NR);

ALTER USER FLAKEBENCH SET NETWORK_POLICY = FLAKEBENCH_GUEST_NP;

-- 4. Create auth policy allowing password + PATs
CREATE AUTHENTICATION POLICY IF NOT EXISTS FLAKEBENCH.PUBLIC.FLAKEBENCH_GUEST_AUTH_POLICY
  AUTHENTICATION_METHODS = ('PASSWORD', 'PROGRAMMATIC_ACCESS_TOKEN')
  MFA_ENROLLMENT = 'OPTIONAL'
  PAT_POLICY = (
    NETWORK_POLICY_EVALUATION = ENFORCED_REQUIRED,
    MAX_EXPIRY_IN_DAYS = 90,
    DEFAULT_EXPIRY_IN_DAYS = 30
  );

ALTER USER FLAKEBENCH SET AUTHENTICATION POLICY FLAKEBENCH.PUBLIC.FLAKEBENCH_GUEST_AUTH_POLICY;

-- 5. Generate PAT scoped to the guest role (30-day expiry)
ALTER USER FLAKEBENCH ADD PROGRAMMATIC ACCESS TOKEN FLAKEBENCH_PAT
  ROLE_RESTRICTION = 'FLAKEBENCH_APP_GUEST_RL'
  DAYS_TO_EXPIRY = 30
  COMMENT = 'Guest access to FlakeBench SPCS app only';

-- 6. Grant service endpoint access
GRANT SERVICE ROLE SANDBOX.SPCS.FLAKEBENCH_SERVICE!ALL_ENDPOINTS_USAGE
  TO ROLE FLAKEBENCH_APP_GUEST_RL;
