-- Diagnostics for test_id=7d08d2f4-683d-44fd-a837-61e4d23cbcf0
USE DATABASE UNISTORE_BENCHMARK;
USE SCHEMA TEST_RESULTS;

-- 1) High-level test summary + config fields
SELECT
  TEST_ID,
  TEST_NAME,
  TABLE_NAME,
  TABLE_TYPE,
  WAREHOUSE,
  STATUS,
  START_TIME,
  END_TIME,
  DURATION_SECONDS,
  CONCURRENT_CONNECTIONS,
  TOTAL_OPERATIONS,
  READ_OPERATIONS,
  WRITE_OPERATIONS,
  FAILED_OPERATIONS,
  ERROR_COUNT,
  ERROR_RATE,
  OPERATIONS_PER_SECOND,
  READS_PER_SECOND,
  WRITES_PER_SECOND,
  P95_LATENCY_MS,
  READ_P95_LATENCY_MS,
  WRITE_P95_LATENCY_MS,
  POINT_LOOKUP_P95_LATENCY_MS,
  RANGE_SCAN_P95_LATENCY_MS,
  INSERT_P95_LATENCY_MS,
  UPDATE_P95_LATENCY_MS,
  TEST_CONFIG:"workload_type"::string AS WORKLOAD_TYPE,
  TEST_CONFIG:"load_mode"::string AS LOAD_MODE,
  TEST_CONFIG:"custom_point_lookup_pct"::number AS CUSTOM_POINT_LOOKUP_PCT,
  TEST_CONFIG:"custom_range_scan_pct"::number AS CUSTOM_RANGE_SCAN_PCT,
  TEST_CONFIG:"custom_insert_pct"::number AS CUSTOM_INSERT_PCT,
  TEST_CONFIG:"custom_update_pct"::number AS CUSTOM_UPDATE_PCT,
  TEST_CONFIG:"collect_query_history"::boolean AS COLLECT_QUERY_HISTORY,
  QUERY_TAG
FROM TEST_RESULTS
WHERE TEST_ID = '7d08d2f4-683d-44fd-a837-61e4d23cbcf0';

-- 2) Persisted per-operation breakdown (if query history capture was enabled for this test)
SELECT
  WARMUP,
  COALESCE(QUERY_KIND, '(NULL)') AS QUERY_KIND,
  COUNT(*) AS N,
  SUM(IFF(SUCCESS, 1, 0)) AS N_SUCCESS,
  SUM(IFF(NOT SUCCESS, 1, 0)) AS N_FAIL,
  ROUND(100 * SUM(IFF(NOT SUCCESS, 1, 0)) / NULLIF(COUNT(*), 0), 2) AS FAIL_PCT,
  ROUND(APPROX_PERCENTILE(APP_ELAPSED_MS, 0.95), 1) AS APP_P95_MS,
  ROUND(APPROX_PERCENTILE(SF_TOTAL_ELAPSED_MS, 0.95), 1) AS SF_TOTAL_P95_MS,
  ROUND(APPROX_PERCENTILE(SF_EXECUTION_MS, 0.95), 1) AS SF_EXEC_P95_MS,
  ROUND(APPROX_PERCENTILE(SF_TX_BLOCKED_MS, 0.95), 1) AS SF_TX_BLOCKED_P95_MS,
  ROUND(APPROX_PERCENTILE(SF_QUEUED_OVERLOAD_MS, 0.95), 1) AS SF_QUEUE_OVERLOAD_P95_MS
FROM QUERY_EXECUTIONS
WHERE TEST_ID = '7d08d2f4-683d-44fd-a837-61e4d23cbcf0'
GROUP BY 1, 2
ORDER BY WARMUP, N_FAIL DESC, N DESC;

-- 3) Top error signatures by query kind
SELECT
  WARMUP,
  COALESCE(QUERY_KIND, '(NULL)') AS QUERY_KIND,
  LEFT(COALESCE(ERROR, ''), 200) AS ERROR_PREFIX,
  COUNT(*) AS N
FROM QUERY_EXECUTIONS
WHERE TEST_ID = '7d08d2f4-683d-44fd-a837-61e4d23cbcf0'
  AND NOT SUCCESS
GROUP BY 1, 2, 3
ORDER BY N DESC
LIMIT 50;

-- 4) Snowflake account-level query history for this test tag (even if per-op capture was disabled)
WITH TR AS (
  SELECT QUERY_TAG
  FROM TEST_RESULTS
  WHERE TEST_ID = '7d08d2f4-683d-44fd-a837-61e4d23cbcf0'
),
QH AS (
  SELECT
    QUERY_TYPE,
    ERROR_CODE,
    ERROR_MESSAGE,
    TOTAL_ELAPSED_TIME,
    EXECUTION_TIME,
    QUEUED_OVERLOAD_TIME,
    QUEUED_PROVISIONING_TIME,
    TRANSACTION_BLOCKED_TIME
  FROM TABLE(
    INFORMATION_SCHEMA.QUERY_HISTORY(
      END_TIME_RANGE_START => DATEADD('hour', -12, CURRENT_TIMESTAMP()),
      END_TIME_RANGE_END => CURRENT_TIMESTAMP(),
      RESULT_LIMIT => 10000
    )
  )
  WHERE QUERY_TAG = (SELECT QUERY_TAG FROM TR)
)
SELECT
  COALESCE(QUERY_TYPE, '(NULL)') AS QUERY_TYPE,
  COALESCE(ERROR_CODE, 0) AS ERROR_CODE,
  LEFT(COALESCE(ERROR_MESSAGE, ''), 200) AS ERROR_PREFIX,
  COUNT(*) AS N,
  ROUND(APPROX_PERCENTILE(TOTAL_ELAPSED_TIME, 0.95), 1) AS TOTAL_P95_MS,
  ROUND(APPROX_PERCENTILE(EXECUTION_TIME, 0.95), 1) AS EXEC_P95_MS,
  ROUND(APPROX_PERCENTILE(TRANSACTION_BLOCKED_TIME, 0.95), 1) AS TX_BLOCKED_P95_MS,
  ROUND(APPROX_PERCENTILE(QUEUED_OVERLOAD_TIME, 0.95), 1) AS QUEUED_OVERLOAD_P95_MS
FROM QH
GROUP BY 1, 2, 3
ORDER BY N DESC
LIMIT 50;

